module.exports = {
  apps : [{
    name: 'pyserver',
    interpreter: "/Users/Teamwork Analytics/AppData/Local/Programs/Python/Python310/python.exe",
    cwd: 'py-server',
    cmd: "server.py",
    autorestart: false,
    watch: false,
    instances: 1,
    pid: 'server.pid',
  }, {
    name: 'pyserver-visualiser',
    interpreter: "/Users/Teamwork Analytics/AppData/Local/Programs/Python/Python310/python.exe",
    cwd: 'py-server',
    cmd: 'server-visualiser.py',
    autorestart: false,
    watch: false,
    instances: 1,
    pid: 'server-visualiser.pid',
  },{
    name: 'client',
    cwd: 'client',
    script: 'node_modules/react-scripts/bin/react-scripts.js',
    args: "start",
    autorestart: false,
    watch: false,
    instances: 1,
    pid: 'client.pid',
    env: {
        PORT:"3000",
    }
  }, {
    name: 'server',
    cwd: 'server',
    script: 'node',
    args: "server.js",
    autorestart: false,
    watch: false,
    instances: 1,
    pid: 'server/server.pid',
  }, {
    name: 'fitbitserver',
    cwd: 'fitbit-receiver',
    script: 'node',
    args: "server.js",
    autorestart: false,
    watch: false,
    instances: 1,
    pid: 'fitbit-receiver/fitbit-receiver.pid',
  }, 
],
};
