module.exports = {
  apps : [{
    name: 'pyserver',
    //interpreter: "py-server/env/Scripts/python.exe",
    cmd: "py-server/server.py",
    script: "py-server/env/Scripts/python.exe",
    interpreter: "none",
    autorestart: false,
    watch: false,
    instances: 1,
    pid: 'py-server/server.pid',
  }, {
    name: 'pyserver-visualiser',
    cmd: 'py-server/server-visualiser.py',
    script: "py-server/env/Scripts/python.exe",
    interpreter: "none",
    autorestart: false,
    watch: false,
    instances: 1,
    pid: 'py-server/server-visualiser.pid',
  },{
    name: 'client',
    cwd: 'client',
    script: 'node_modules/react-scripts/bin/react-scripts.js',
    args: "start",
    autorestart: false,
    watch: false,
    instances: 1,
    pid: 'client/client.pid',
    env: {
        PORT:"3000",
    }
  }, {
    name: 'server',
    cwd: 'server',
    script: 'node',
    args: "server.js",
    autorestart: false,
    watch: false,
    instances: 1,
    pid: 'server/server.pid',
  }, {
    name: 'fitbitserver',
    cwd: 'fitbit-receiver',
    script: 'node',
    args: "server.js",
    autorestart: false,
    watch: false,
    instances: 1,
    pid: 'fitbit-receiver/fitbit-receiver.pid',
  }, 
],
};
